import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { ContractContextProvider } from "@/context/contract";
import { Ubuntu } from "next/font/google";
import {Toaster} from "react-hot-toast"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300","400","500","700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${ubuntu.className} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-right"/>
        <ContractContextProvider>
        <Navbar />

          {children}

        </ContractContextProvider>
        <Footer />
      </body>
    </html>
  );
}
